version: "3.9"

services:
  minio:
    image: minio/minio:RELEASE.2024-09-09T16-59-28Z
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: deltadmin
      MINIO_ROOT_PASSWORD: deltasecret
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  minio-setup:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: /bin/sh
    command: -c "mc alias set local http://minio:9000 deltadmin deltasecret && mc mb -p local/dg-demo || true"

  backend:
    build: .
    environment:
      AWS_ACCESS_KEY_ID: deltadmin
      AWS_SECRET_ACCESS_KEY: deltasecret
      AWS_DEFAULT_REGION: us-east-1
      DGCOMM_S3_ENDPOINT: http://minio:9000
      DGCOMM_S3_ADDRESSING_STYLE: path
      DGCOMM_HMAC_SECRET: dev-secret
    depends_on:
      - minio-setup
    ports:
      - "8000:8000"
    volumes:
      - ./releases:/app/releases:ro

  seed:
    build: .
    command: python -m dgcommander.scripts.seed_minio
    environment:
      AWS_ACCESS_KEY_ID: deltadmin
      AWS_SECRET_ACCESS_KEY: deltasecret
      AWS_DEFAULT_REGION: us-east-1
      DGCOMM_S3_ENDPOINT: http://minio:9000
      DGCOMM_S3_ADDRESSING_STYLE: path
      DGCOMM_CACHE_DIR: /tmp/dgcommander-cache
      DGCOMM_SEED_BUCKET: dg-demo
    depends_on:
      - minio-setup
    profiles: ["tools"]

volumes:
  minio-data:
