# Production Docker Compose example
#
# Usage:
#   1. Copy this file and create a .env file with your secrets
#   2. docker compose -f docker-compose.prod.yml up -d
#   3. Navigate to http://localhost:8000/settings to configure S3 credentials
#
# Required .env variables:
#   DGCOMM_HMAC_SECRET  - Secret for signing download tokens (generate with: openssl rand -hex 32)
#
# NOTE: S3/AWS credentials are no longer configured via environment variables.
# After starting the container, configure your S3 credentials through the web UI
# at http://localhost:8000/settings

version: "3.9"

services:
  dgcommander:
    image: beshultd/deltaglider_commander:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # Security (Required)
      DGCOMM_HMAC_SECRET: ${DGCOMM_HMAC_SECRET}

      # Optional Configuration
      DGCOMM_CACHE_DIR: ${DGCOMM_CACHE_DIR:-/tmp/dgcommander-cache}
      DGCOMM_OBJECT_RATE_LIMIT: ${DGCOMM_OBJECT_RATE_LIMIT:-10}
      DGCOMM_OBJECT_RATE_WINDOW: ${DGCOMM_OBJECT_RATE_WINDOW:-1.0}
      DGCOMM_DOWNLOAD_TTL: ${DGCOMM_DOWNLOAD_TTL:-300}
    
    # Optional: mount cache directory for persistence
    # volumes:
    #   - ./cache:/tmp/dgcommander-cache
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/test/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
